### ISSUE TITLE
Update for Phoenix 1.3?

### ISSUE THREAD

**Issue by mattcree** [wtfleming/phoenix-postgis-example#2]
I'm having some trouble applying what you've done here to Phoenix 1.3. Mostly because of the new contexts and web/ stuff ending up in lib/.

Do you think you'll update this project at some point?

**Comment by wtfleming** [comment]
I'd like to update it at some point, but not sure when i'll have the time, i'm moving to a new city and about to start a new job, just don't have the bandwidth right now.
