### ISSUE TITLE
geometry type not loading

### ISSUE THREAD

**Issue by shirawebill** [wtfleming/phoenix-postgis-example#5]
Hi,
I am using geometry in a project exactly the way you have in this project - I followed all the examples on
https://wtfleming.github.io/blog/geospatial-app-elixir-postgis-phoenix/
I am still getting this error:
 
**create table sites
** (Postgrex.Error) ERROR 42704 (undefined_object) type "geometry" does not exist**

Please advise?

Also -  this is the error I get when the  type geometry does load and I run the tests:
** (DBConnection.EncodeError) Postgrex expected an integer in -9223372036854775808..9223372036854775807, got <<66, 206, 117, 40, 187, 17, 71, 158, 148, 177, 21, 169, 99, 91, 189, 152>>. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.

https://github.com/shirawebill/wb_portfolio_persistence

**Comment by wtfleming** [comment]
Hi,
I haven't looked at this code in a number of years and not sure how helpful I'll be, but a couple things

At https://github.com/shirawebill/wb_portfolio_persistence/blob/main/mix.exs it looks like you are using `{:geo, "~> 3.4.2"}` and in the blog post code at https://github.com/wtfleming/phoenix-postgis-example/blob/master/mix.exs it uses `{:geo, "~> 1.4"}`

There is a large enough difference between those versions that something may have changed.

Also, are you sure you have postgis installed correctly? That could be the problem - a potential solution might be in this thread https://github.com/bryanjos/geo/issues/15

**Comment by shirawebill** [comment]
Hi,

Thank you very much for your help. 

I definitely have postgis installed correctly - I checked in pgAdmin

I think it does have something to do with the version; after following all the steps and doing as per the above link, I still have not managed to fix it. (I am one version higher than they had). 

In the meantime, I have changed the type to be jsonb - instead of geometry, and the geo types are working in the schema. 
However my tests still aren't running - do you have any idea what is wrong with my sites input?

Attached are images of my site schemas and tests

![image](https://user-images.githubusercontent.com/86683313/145176662-4848298f-11dd-4cf1-ac7e-86db092f0dbb.png)

![image](https://user-images.githubusercontent.com/86683313/145176817-2885a569-ad72-4d35-9c87-4ba16fb6558d.png)

![image](https://user-images.githubusercontent.com/86683313/145177464-8cf9d2ac-ce80-4375-b0e1-343ea5521d2f.png)

![image](https://user-images.githubusercontent.com/86683313/145177001-8597bf22-05f2-4649-87eb-7648e18fb8ea.png)

![image](https://user-images.githubusercontent.com/86683313/145200839-c684f38d-62bf-42b6-8198-a846eed3dee0.png)

Regards,
Shira

**Comment by wtfleming** [comment]
I'm not sure what is going on. Sorry I can't be more help, it's been awhile since I've written any Elixir or looked at this code

**Comment by shirawebill** [comment]
No problem, I managed to figure it out, thank you for your help.

**Comment by wtfleming** [comment]
Glad to hear you got it working. Cheers.
